language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - yarn lint
  - yarn test
  - yarn create-docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  local_dir: docs
  on:
    branch: master
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
